name: CS checker
on: 
  push:
    branches:
      - "**"
jobs:
  linter_name:
    name: runner / phpcs
    runs-on: blackstone
    steps:
      - uses: actions/checkout@v2
      - uses: roanokecollege/phpcs-action@master
        with:
          github_token: ${{ secrets.github_token }}
          use_default_configuration_file: true
          phpcs_args: '-n' # ignore warnings
      - uses: stefanzweifel/git-auto-commit-action@v4 # auto commit the fixes action for GitHub
        with:
          commit_message: Fix PHPCS errors
  annotate:
    name: codesniffer
    runs-on: ubuntu-latest
    steps:
      - uses: tinovyatkin/action-php-codesniffer@v1
        with:
          files: "**.php" # you may customize glob as needed
          phpcs_path: php phpcs.phar
          standard: phpcs.xml          
